# Generated by Django 4.1.6 on 2023-03-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_category_order_alter_customuser_phone_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(help_text='Enter 10 digits phone number', max_length=10, unique=True, verbose_name='Phone Number'),
        ),
    ]
