# Generated by Django 4.1.6 on 2023-04-09 06:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
